language: python
fast_finish: true

python:
  - 2.7
  - 3.6

os:
  - linux


git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

before_install:
    # temp for pip < 9.1
    - pip -q install numpy

install: pip install -e .[tests]

script: coverage run tests/test_all.py -v

after_success: coveralls
