name: ci

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
    - "**.py"
    - ".github/workflows/ci.yml"

jobs:

  core:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ['3.9', '3.11']

    env:
      FC: gfortran-11

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - run: pip install .[tests,lint]
      timeout-minutes: 2

    - run: flake8
    - run: mypy

    - run: pytest

    # - run: pip install codecov pytest-cov
    # - run: pytest --cov --cov-report=xml
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1
